apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  labels:
    app: console
data:
  config.js: |
    window.clusterConfig = {
      domain: '%DOMAIN%',
      pamelaApiUrl: 'https://pamela.%DOMAIN%',
    };
